/* Spacing */
const kSpacing1 = 8.0;
const kSpacing2 = 16.0;
const kSpacing3 = 24.0;
const kSpacing4 = 32.0;
const kSpacing5 = 40.0;
const kSpacing6 = 48.0;
const kSpacing7 = 56.0;
const kSpacing8 = 64.0;
const kSpacing9 = 72.0;
const kSpacing10 = 80.0;
const kSpacing11 = 88.0;
const kSpacing12 = 96.0;
const kSpacing13 = 104.0;
const kSpacing14 = 112.0;
const kSpacing15 = 120.0;
const kSpacing16 = 128.0;
const kSpacing17 = 136.0;
const kSpacing18 = 144.0;
const kSpacing19 = 152.0;
const kSpacing20 = 160.0;
/* Firebase collections */
const merchantsCollection = 'merchants';
const productsSubcollection = 'products';
const promosSubcollection = 'promos';
const allProductsCollection = 'all-products';
const allPromosCollection = 'all-promos';
/* PageView ids */
const kLandingFlowPageViewId = 'landing-flow';
const kOnboardingFlowPageViewId = 'onboarding-flow';
const kCarouselPageViewId = 'carousel';
const kReceiveSatsFlowPageViewId = 'receive-sats-flow';
const kSendSatsFlowPageViewId = 'send-sats-flow';
const kPromoFlowPageViewId = 'promo-flow';
const kCashierFlowPageViewId = 'cashier-flow';
const kPromoValidationFlowPageViewId = 'promo-validation-flow';
const kAddContactFlowPageViewId = 'add-contact-flow';
const kSeedBackupFlowPageViewId = 'seed-backup-flow';
const kSeedImportFlowPageViewId = 'seed-recovery-flow';
/* Secure storage keys */
const kMnemonicKey = 'mnemonic';
const kMnemonicLanguageKey = 'mnemonic-language';
const kPinDigestKey = 'pin-digest';
/* Settings keys */
const kBitcoinUnitSettingsKey = 'bitcoin-unit-settings';
const kLocalCurrencySettingsKey = 'local-currency-settings';
const kLocationSettingsKey = 'location-settings';
/* Database tables */
const kContactsTable = 'Contacts';
const kChatMessagesTable = 'ChatMessages';
/* List limits */
const kChatMessagesLimit = 6;
const kPaymentsLimit = 20;
const kContactListLimit = 10;
const kFrequentContactsLimit = 10;
const kMyPostsLimit = 10;
/* Other */
const kMaxSeedEntropyLength = 256;
const kSeedEntropyLength = 128;
const kInviteCodeLength = 9;
const kPinLength = 4;
const kBreezSdkWorkingDirName = 'breezSdk';
